import type { Template } from "@/types";

/** Website templates */
export const templates: Template[] = [
  {
    id: "t1",
    title: "Starter Business",
    slug: "starter-business",
    category: "Company Profile",
    description: "Clean and professional template for startups and small businesses looking to establish their online presence.",
    image: "/images/template-1.jpg",
    features: ["Hero Section", "About Us", "Services", "Contact Form", "Responsive"],
    price: "Rp 150,000",
    popular: true,
  },
  {
    id: "t2",
    title: "Modern Agency",
    slug: "modern-agency",
    category: "Agency",
    description: "Bold and creative template designed for digital agencies and creative studios.",
    image: "/images/template-2.jpg",
    features: ["Portfolio Grid", "Team Section", "Testimonials", "Blog Ready", "Dark Mode"],
    price: "Rp 250,000",
  },
  {
    id: "t3",
    title: "E-Commerce Pro",
    slug: "ecommerce-pro",
    category: "E-Commerce",
    description: "Feature-rich e-commerce template with product catalog, cart, and checkout flow.",
    image: "/images/template-3.jpg",
    features: ["Product Grid", "Shopping Cart", "Checkout Flow", "Filter System", "Wishlist"],
    price: "Rp 350,000",
    popular: true,
  },
  {
    id: "t4",
    title: "Tech Startup",
    slug: "tech-startup",
    category: "SaaS",
    description: "Sleek template for SaaS companies and tech startups with pricing tables and feature showcases.",
    image: "/images/template-4.jpg",
    features: ["Pricing Tables", "Feature Showcase", "Integration Section", "FAQ Accordion", "CTA Sections"],
    price: "Rp 300,000",
  },
  {
    id: "t5",
    title: "Restaurant Elite",
    slug: "restaurant-elite",
    category: "Food & Beverage",
    description: "Appetizing template for restaurants, cafes, and food businesses with menu display.",
    image: "/images/template-5.jpg",
    features: ["Menu Display", "Reservation Form", "Gallery", "Location Map", "Online Ordering"],
    price: "Rp 200,000",
  },
  {
    id: "t6",
    title: "Health Clinic",
    slug: "health-clinic",
    category: "Healthcare",
    description: "Trust-building template for clinics, doctors, and healthcare providers.",
    image: "/images/template-6.jpg",
    features: ["Doctor Profiles", "Service List", "Appointment Booking", "Testimonials", "Health Blog"],
    price: "Rp 250,000",
  },
  // --- Company Profile ---
  {
    id: "t7",
    title: "Minimalist Corporate",
    slug: "minimal-corporate",
    category: "Company Profile",
    description: "Ultra-clean minimalist template for corporations that value simplicity and elegance.",
    image: "/images/template-7.jpg",
    features: ["Minimal Hero", "Company Overview", "Team Section", "Contact Form", "Responsive"],
    price: "Rp 175,000",
  },
  {
    id: "t8",
    title: "Creative Studio",
    slug: "creative-studio",
    category: "Company Profile",
    description: "Vibrant and artistic template for creative businesses and studios.",
    image: "/images/template-8.jpg",
    features: ["Animated Hero", "Portfolio Showcase", "Services Grid", "Blog Section", "Dark Mode"],
    price: "Rp 200,000",
    popular: true,
  },
  {
    id: "t9",
    title: "Enterprise Corp",
    slug: "enterprise-corp",
    category: "Company Profile",
    description: "Professional and trustworthy template for large enterprises and corporations.",
    image: "/images/template-9.jpg",
    features: ["Corporate Hero", "Milestones Timeline", "Investor Relations", "CSR Section", "Multi-language"],
    price: "Rp 300,000",
  },
  // --- Agency ---
  {
    id: "t10",
    title: "Marketing Hub",
    slug: "marketing-hub",
    category: "Agency",
    description: "Dynamic template for marketing agencies with bold visuals and case studies.",
    image: "/images/template-10.jpg",
    features: ["Case Studies", "Service Packages", "ROI Calculator", "Client Logos", "Blog"],
    price: "Rp 275,000",
  },
  {
    id: "t11",
    title: "Digital Agency",
    slug: "digital-agency",
    category: "Agency",
    description: "Sleek and modern template for digital agencies and tech-forward studios.",
    image: "/images/template-11.jpg",
    features: ["Project Showcase", "Tech Stack Display", "Process Steps", "Pricing Cards", "Testimonials"],
    price: "Rp 250,000",
  },
  {
    id: "t12",
    title: "Brand Studio",
    slug: "brand-studio",
    category: "Agency",
    description: "Elegant template focused on branding services and visual identity work.",
    image: "/images/template-12.jpg",
    features: ["Brand Showcase", "Before/After", "Design Process", "Package Tiers", "Contact"],
    price: "Rp 225,000",
  },
  // --- E-Commerce ---
  {
    id: "t13",
    title: "Fashion Store",
    slug: "fashion-store",
    category: "E-Commerce",
    description: "Stylish e-commerce template for fashion brands and clothing stores.",
    image: "/images/template-13.jpg",
    features: ["Lookbook Gallery", "Size Guide", "Quick View", "Wishlist", "Social Proof"],
    price: "Rp 350,000",
    popular: true,
  },
  {
    id: "t14",
    title: "Tech Marketplace",
    slug: "tech-marketplace",
    category: "E-Commerce",
    description: "Clean and technical template for electronics and gadget stores.",
    image: "/images/template-14.jpg",
    features: ["Product Comparison", "Spec Sheets", "Review System", "Category Filter", "Deals Section"],
    price: "Rp 375,000",
  },
  {
    id: "t15",
    title: "Organic Market",
    slug: "organic-market",
    category: "E-Commerce",
    description: "Earthy and natural template for organic food and wellness product stores.",
    image: "/images/template-15.jpg",
    features: ["Farm Story", "Product Categories", "Subscription Box", "Recipe Blog", "Sustainability"],
    price: "Rp 300,000",
  },
  // --- SaaS ---
  {
    id: "t16",
    title: "Analytics Dashboard",
    slug: "analytics-dashboard",
    category: "SaaS",
    description: "Data-driven template for analytics platforms and business intelligence tools.",
    image: "/images/template-16.jpg",
    features: ["Dashboard Preview", "Metric Cards", "Integration Grid", "Documentation", "API Reference"],
    price: "Rp 325,000",
  },
  {
    id: "t17",
    title: "Project Manager",
    slug: "project-manager",
    category: "SaaS",
    description: "Clean and organized template for project management and productivity tools.",
    image: "/images/template-17.jpg",
    features: ["Kanban Preview", "Feature Comparison", "Use Cases", "Changelog", "Roadmap"],
    price: "Rp 300,000",
  },
  {
    id: "t18",
    title: "CRM Platform",
    slug: "crm-platform",
    category: "SaaS",
    description: "Professional template for CRM and customer relationship management platforms.",
    image: "/images/template-18.jpg",
    features: ["CRM Dashboard", "Pipeline View", "Contact Management", "Reporting", "Integrations"],
    price: "Rp 350,000",
  },
  // --- Food & Beverage ---
  {
    id: "t19",
    title: "Coffee Shop",
    slug: "coffee-shop",
    category: "Food & Beverage",
    description: "Warm and inviting template for coffee shops and cafes.",
    image: "/images/template-19.jpg",
    features: ["Menu Display", "Coffee Origins", "Ambiance Gallery", "Loyalty Program", "Location Map"],
    price: "Rp 175,000",
    popular: true,
  },
  {
    id: "t20",
    title: "Bakery & Sweets",
    slug: "bakery-sweets",
    category: "Food & Beverage",
    description: "Sweet and charming template for bakeries, pastry shops, and dessert cafes.",
    image: "/images/template-20.jpg",
    features: ["Product Showcase", "Custom Orders", "Daily Specials", "Instagram Feed", "Pre-Order Form"],
    price: "Rp 180,000",
  },
  {
    id: "t21",
    title: "Bar & Grill",
    slug: "bar-grill",
    category: "Food & Beverage",
    description: "Bold and energetic template for bars, grills, and nightlife venues.",
    image: "/images/template-21.jpg",
    features: ["Drink Menu", "Event Calendar", "Happy Hour Deals", "Photo Gallery", "Reservation"],
    price: "Rp 200,000",
  },
  // --- Healthcare ---
  {
    id: "t22",
    title: "Dental Care",
    slug: "dental-care",
    category: "Healthcare",
    description: "Bright and friendly template for dental clinics and orthodontic practices.",
    image: "/images/template-22.jpg",
    features: ["Service List", "Before/After Gallery", "Insurance Info", "Online Booking", "Patient Forms"],
    price: "Rp 225,000",
  },
  {
    id: "t23",
    title: "Pharma Plus",
    slug: "pharma-plus",
    category: "Healthcare",
    description: "Professional template for pharmacies, pharmaceutical companies, and drugstores.",
    image: "/images/template-23.jpg",
    features: ["Product Catalog", "Drug Information", "Refill Reminders", "Delivery Service", "Health Tips"],
    price: "Rp 200,000",
  },
  {
    id: "t24",
    title: "Wellness Center",
    slug: "wellness-center",
    category: "Healthcare",
    description: "Calm and serene template for wellness centers, spas, and holistic health providers.",
    image: "/images/template-24.jpg",
    features: ["Treatment Menu", "Therapist Profiles", "Booking System", "Wellness Blog", "Gift Cards"],
    price: "Rp 250,000",
  },
];
